### ISSUE TITLE
Testnet  Unable to sync

### ISSUE THREAD

**Issue by hzccc** [icon-project/loopchain#593]
[2020-11-12 15:54:30.781] RPC_PORT: 9000 / RPC_WORKER: 3   
  [2020-11-12 15:54:30.786] DEFAULT_PATH=/data/loopchain in Docker Container  
  [2020-11-12 15:54:30.791] DEFAULT_LOG_PATH=/data/loopchain/log  
  [2020-11-12 15:54:30.795] DEFAULT_STORAGE_PATH=/data/loopchain/.storage  
  [2020-11-12 15:54:30.799] scoreRootPath=/data/loopchain/.score_data/score  
  [2020-11-12 15:54:30.804] stateDbRootPath=/data/loopchain/.score_data/db  
  [2020-11-12 15:54:30.809] GENESIS_DATA_PATH=/prep_peer/conf/genesis.json  
  [2020-11-12 15:54:30.813] P-REP package version info - prep-node_2009031457xdaf395  

  [2020-11-12 15:54:36.674] iconcommons             1.1.3
iconrpcserver           1.5.1
iconsdk                 1.3.2
iconservice             1.7.7
loopchain               2.6.0  
  [2020-11-12 15:54:36.679] NETWORK_ENV=testnet, SERVICE=testnet, ENDPOINT_URL=0.0.0.0:9000, SERVICE_API=0.0.0.0:9000/api/v3  
  [2020-11-12 15:54:36.690] Already cert keys= /cert/keystore.json  
  [2020-11-12 15:54:37.227] Peer ID: hx354f1375ecda9f6df7b121a80c9001ad22449e6d  
  [2020-11-12 15:54:37.244] SWITCH_BH_VERSION3 = 1  
  [2020-11-12 15:54:37.253] SWITCH_BH_VERSION4 = 10  
  [2020-11-12 15:54:37.261] SWITCH_BH_VERSION5 = 524360  
curl: (7) Failed to connect to 0.0.0.0 port 9000: Connection refused
  [2020-11-12 15:54:37.322] UnRegistered P-Rep Network   
curl: (22) The requested URL returned error: 403 
  [2020-11-12 15:54:39.352] == IP targets is null  
  [2020-11-12 15:54:39.357] CHANNEL_MANAGE_DATA not found - /prep_peer/conf/channel_manange_data.json  
0
  [2020-11-12 15:54:39.470] START FASTEST MODE : NETWORK_NAME=TestctzNet  
  [2020-11-12 15:54:39.478] [PASS] Already file - /data/loopchain/TestctzNet_BH13221242_data-20201112_1500.tar.gz  
Wait for rabbitmq-server(127.0.0.1) / USE_EXTERNAL_MQ: false - sleeping
Wait for rabbitmq-server(127.0.0.1) / USE_EXTERNAL_MQ: false - sleeping
Wait for rabbitmq-server(127.0.0.1) / USE_EXTERNAL_MQ: false - sleeping
Wait for rabbitmq-server(127.0.0.1) / USE_EXTERNAL_MQ: false - sleeping

  ####RabbitMQ 3.7.23. Copyright (C) 2007-2019 Pivotal Software, Inc.
  ##########Licensed under the MPL.  See https://www.rabbitmq.com/
  ########
  ##########Logs: /var/log/rabbitmq/rabbit@4d45ee46aaa6.log
                    /var/log/rabbitmq/rabbit@4d45ee46aaa6_upgrade.log

Starting broker...
 completed with 0 plugins.
  [2020-11-12 15:54:43.514] Network: testnet / RUN_MODE: '' / LOG_OUTPUT_TYPE: file  
  [2020-11-12 15:54:43.522] [OK] CHECK=0, Run loop-peer and loop-channel start -> ''  
  [2020-11-12 15:54:43.543] [OK] CHECK=0, Run iconrpcserver start!  
[*] To exit press CTRL+C
[2020-11-12 15:54:45 +0900] [519] [INFO] Starting gunicorn 20.0.4
[2020-11-12 15:54:45 +0900] [519] [INFO] Listening at: http://0.0.0.0:9000 (519)
[2020-11-12 15:54:45 +0900] [519] [INFO] Using worker: sanic.worker.GunicornWorker
[2020-11-12 15:54:45 +0900] [538] [INFO] Booting worker with pid: 538
[2020-11-12 15:54:45 +0900] [539] [INFO] Booting worker with pid: 539
[2020-11-12 15:54:45 +0900] [540] [INFO] Booting worker with pid: 540
ERROR:root:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jsonrpcserver/dispatcher.py", line 123, in handle_exceptions
    yield handler
  File "/usr/local/lib/python3.7/site-packages/jsonrpcserver/async_dispatcher.py", line 40, in safe_call
    lookup(methods, request.method), *request.args, **request.kwargs
  File "/usr/local/lib/python3.7/site-packages/jsonrpcserver/async_dispatcher.py", line 34, in call
    return await validate_args(method, *args, **kwargs)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/iconrpcserver/dispatcher/v3/rep.py", line 32, in rep_getListByHash
    reps = await channel_stub.async_task().get_reps_by_hash(reps_hash=reps_hash)
  File "/usr/local/lib/python3.7/site-packages/earlgrey/message_queue_stub.py", line 128, in _call_async_rpc
    result = await self._rpc_client_async.call(func_name, kwargs=params.arguments, priority=priority)
  File "/usr/local/lib/python3.7/site-packages/earlgrey/patterns/rpc/client_async.py", line 131, in call
    return (yield from future)
concurrent.futures._base.CancelledError
  [2020-11-12 15:55:28.585] Start Health check ... 30s, HEALTH_ENV_CHECK=true  
  [2020-11-12 15:55:59.398] == [OK] Write json file -> /.docker_info, 51.0 bytes
IP targets is null  
  [2020-11-12 15:55:59.439] BlockCheck: BH=0, TX=0, UN_TX=0, state=EvaluateNetwork  
  [2020-11-12 15:55:59.447] Time synchronization with NTP / NTP SERVER: time.google.com - 1  

 [2020-11-12 15:56:16.289] [ERROR] [FAIL] Time Synchronization!!  
  [2020-11-12 15:56:46.508] == IP targets is null  
  [2020-11-12 15:56:46.548] BlockCheck: BH=0, TX=0, UN_TX=0, state=EvaluateNetwork  
 [2020-11-12 15:57:03.385] [ERROR] [FAIL] Time Synchronization!!  
  [2020-11-12 15:57:33.599] == IP targets is null  
  [2020-11-12 15:57:33.637] BlockCheck: BH=0, TX=0, UN_TX=0, state=EvaluateNetwork  
 [2020-11-12 15:57:50.452] [ERROR] [FAIL] Time Synchronization!!  

docker-compose 
```yaml
version: '3'
services:
   prep-node:
      image: 'iconloop/prep-node'
      container_name: "prep-testnet"
      restart: "always"
      environment:
         LOOPCHAIN_LOG_LEVEL: "DEBUG"
         ICON_LOG_LEVEL: "DEBUG"
         NETWORK_ENV: "testnet"
         DEFAULT_PATH: "/data/loopchain"
         LOG_OUTPUT_TYPE: "file"
         PRIVATE_PATH: "/cert/keystore.json"
         PRIVATE_PASSWORD: "icon.123456"
         CERT_PATH: "/cert"
         ENDPOINT_URL: "0.0.0.0:9000"
         SERVICE: "zicon"
         FASTEST_START: "yes"
      cap_add:
         - SYS_TIME
      volumes:
         - ./data:/data
         - ./cert:/cert:ro
      ports:
         - '7100:7100'
         - '9000:9000'
~                       
```
